### ISSUE TITLE
Hack got glitched out with Animations and Visible by enemy Logic

### ISSUE THREAD

**Issue by snajdovski** [darksoul577/ReShade#2]
When injected the heroes don't have animations and the visible by enemy is broken. Probably the offsets changed.
Could you point out how did you find them so I can update them?

**Comment by darksoul577** [comment]
Sounds like the offsets for the C_BaseModelEntity vtable have changed. I used as few functions as possible so that it would be easy to keep up with the frequent dota updates. You need IDA, which is available for free, and the ClassInformer plugin (also free). 

Load an old client.dll file from when the cheat was working into IDA. Run your ClassInformer plugin. Look at the functions that are at the offsets that we access in the C_BaseModelEntity vtable. 

Then load the new client.dll file and run ClassInformer. Compare the functions that are at the offsets to see how they have shifted. Usually they only get moved a few places, so it's easy to see the new offsets.

Once you have your new offsets just plug them into your program and you're good to go. Once you do it a few times it's fairly fast.

**Comment by darksoul577** [comment]
One other thing-- the vtable function that we use for visibility by enemy is CanBeSeenByTeam, which was previously at 215th offset of the C_BaseModelEntity vtable.

**Comment by snajdovski** [comment]
Alright, I wiped my drive so I will need to redownload dota, lol I will keep you updated if I get stuck, I have like some knowledge with IDA. I will close the issue for now.
Is that ok?

**Comment by darksoul577** [comment]
Sure. Good luck!

**Comment by newwide** [comment]
I scanned the visible by enemy offset using CE. 

0054CFB0 0 28 38 70 170 0 1E4

**Comment by JEJC** [comment]
you can share it already compiled

**Comment by newwide** [comment]
> you can share it already compiled

Sorry man, I do not know how to code and change the offset.

**Comment by JEJC** [comment]
> When injected the heroes don't have animations and the visible by enemy is broken. Probably the offsets changed.
> Could you point out how did you find them so I can update them?

you can share it already compiled
