### ISSUE TITLE
Is it possible to remove everything except the TP maphack?

### ISSUE THREAD

**Issue by newwide** [darksoul577/ReShade#3]
Could you provide a source code with only maphack or point out where to remove the expired function?(Like visible detection and glitch movement)?

Tried to follow the previous instruction but it is out of my knowledge area.
![image](https://user-images.githubusercontent.com/69209831/93076055-57c2fa80-f6b9-11ea-8eb1-a43c317c1647.png)

**Comment by snajdovski** [comment]
I think you cant because tp particles are within the particle manager they are basicly particles. If you want to exclude the other particles you would need to find the tp_scroll particle and exclude others with loops and if statements.That would be very slow imo.

**Comment by darksoul577** [comment]
I posted a quick tutorial for how to update the dota hack:

https://guidedhacking.com/threads/dota-2-cheats-maphack-illusion-detector-vision-detector.15840/post-99514

Basically, the offset for CanBeSeenByTeam shifted up four spots, so I made that quick update to the CEntityInstance.h file, so that the hack works again.

**Comment by newwide** [comment]
Thanks, learning much from your tutorial. Will learn the whole IDA stuff or even general coding when I have the time. Hopefully in the future I am able to update the offset myself.

**Comment by newwide** [comment]
Just for anyone's info, here's the tutorial to get previous version of steam game.  The current working way is using a depotdownloader. 

https://www.youtube.com/watch?v=JKmIbmPx1sY
